@startuml
class com.sample.activities.CrashActivity {
- Button tryAgainButton
- Button writeMessageButton
# void onCreate(Bundle)
- void setupViews()
~ void restartApplication()
~ void sendEmail()
}


android.app.Activity <|-- com.sample.activities.CrashActivity
@enduml